# Day2: 
- numpy, pandas, matplotlib
- sklearn(머신러닝), kNN, (나이브베이즈), 실습과제

## Numpy

In [1]:
# 객체 생성
from numpy import array
a1 = array([10, 20, 30])
a2 = array([[10, 20, 30], [40, 50, 60]])

# 정보조회 (모양)
print(a1.shape)
print(a2.shape)

(3,)
(2, 3)


In [3]:
# 색인 (정수색인, 슬라이싱, 불리언색인, 팬시색인)
# 정수색인 (차원축소)
print(a1) # array.__str__()
a1[1]

[10 20 30]


20

In [4]:
a1 # array.__repr__()

array([10, 20, 30])

In [11]:
a2[0,1]

20

In [12]:
# 슬라이싱
a1[1:]

array([20, 30])

In [16]:
a2[:1, 1:]

array([[20, 30]])

In [18]:
# 불리언 색인
a1 < 30 # 조건연산을 하면 조건이 참인 요소에 대해서만 True가 됨, 불리언배열

array([ True,  True, False])

In [19]:
a1[array([ True,  True, False])]

array([10, 20])

In [20]:
a1[a1 < 30]

array([10, 20])

In [21]:
# 팬시색인 (정렬)
a1

array([10, 20, 30])

In [23]:
a1[[2, 0]]

array([30, 10])

In [24]:
## 연산 (유니버셜 함수)
# a2의 열별 합계
a2.sum(0)

array([50, 70, 90])

In [25]:
# a2의 행별 합계
a2.sum(1)

array([ 60, 150])

In [26]:
# 브로드캐스팅: 연산가능한 모양으로 맞추는 기능
a2 + 3

array([[13, 23, 33],
       [43, 53, 63]])

In [28]:
a2 + a1 # BC 가능한 모양: BC 방향을 추정할 수 있는 경우 
# (2차원 열의 개수가 1차원의 요소 개수와 동일)

array([[20, 40, 60],
       [50, 70, 90]])

In [29]:
a2 + array([3, 3]) # BC 방향을 추정할 수 있는 경우 

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [32]:
import numpy as np
a3 = np.arange(12).reshape(2, 2, 3)
print(a3.shape)

(2, 2, 3)


In [33]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [37]:
a3 + np.arange(6).reshape(1, 2, 3)

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[ 6,  8, 10],
        [12, 14, 16]]])

In [40]:
# (2, 2, 3) + (4, 2, 3)
a3 + np.arange(24).reshape(4, 2, 3)

ValueError: operands could not be broadcast together with shapes (2,2,3) (4,2,3) 

In [41]:
# 브로드캐스팅은 행렬곱과 같은 다른 연산에서도 가능함
np.dot(a2, a1)

array([1400, 3200])

In [42]:
np.dot(a2, array([3, 3]))

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

## 넘파이 응용

In [48]:
import matplotlib.pyplot as plt
import os

imgpath = os.path.join('C:\\','Users', 'shbaek', 'Downloads', '2022PythonDA3rd-main', '2022PythonDA3rd-main','park.jpg')
print(imgpath)
img = plt.imread(imgpath).copy()
img.shape

C:\Users\shbaek\Downloads\2022PythonDA3rd-main\2022PythonDA3rd-main\park.jpg


(150, 120, 3)

In [49]:
# 휴식 ~ 10:30
import matplotlib.pyplot as plt
import os

img = plt.imread('image.png').copy()
img.shape

(150, 120, 3)

In [50]:
%pwd

'C:\\Users\\shbaek\\workshop'

In [52]:
import shutil
shutil.copy('image.png', 'C:/workshop')

'C:/workshop\\image.png'